### ISSUE TITLE
Multiple crates

### ISSUE THREAD

**Issue by Freyskeyd** [onur/docs.rs#113]
Hello and thank's for this service.

I've a library splitted in 3 crates.

- xmpp-client
- xmpp-proto
- xmpp-rs

`xmpp-rs` is a reexport of client and proto.
`xmpp-client` hold a reference to `xmpp-proto`

But, when I see https://docs.rs/xmpp-client/0.1.1/xmpp_client/struct.Client.html#method.connect

The `Credentials` is unclickable, you can see it here: https://docs.rs/xmpp-proto/0.1.1/xmpp_proto/credentials/struct.Credentials.html

Is it a normal use case? Am I missing something?

**Comment by onur** [comment]
Unfortunately this is one of the limitations of docs.rs. Docs.rs is skipping dependencies (similar to `cargo doc --no-dep`) to avoid duplication and currently there is no way to tell cargo to build only specific dependencies.

**Comment by Freyskeyd** [comment]
mmmh ok, I think I will need to build my own github-page :/

thank's anyway

**Comment by onur** [comment]
@Freyskeyd I'd like to add something. If you configure documentation url correctly docs.rs will use that url for external crates and types as well.

For example check last three function in this page: <https://docs.rs/acme-client/0.4.0/acme_client/struct.SignedCertificate.html>. `X509`, `X509Req` and `PKey` types are member of `openssl` crate and since `openssl` crate is also using docs.rs in documentation url, docs.rs is using correct links for this types.
