### ISSUE TITLE
Links in constants' docs are not resolved

### ISSUE THREAD

**Issue by ljedrz** [onur/docs.rs#119]
It appears that links in constants' docs are not resolved; the example below is correctly recognized as a link when created with `cargo doc`.

[example](https://docs.rs/lambda_calculus/0.6.0/lambda_calculus/reduction/constant.EVALUATION_ORDER.html)

**Comment by onur** [comment]
Thanks for reporting.

Looks like nobody realized this during: rust-lang/rust#40912. rust compiler is causing this problem, it's better if you report this into rust repository.

Docs.rs is currently using `rustc 1.18.0-nightly (bbdaad0dc 2017-04-14)` and I also tested on my PC with `rustc 1.18.0-nightly (bbdaad0dc 2017-04-14)`. This bug exists in both version of rust compilers. IDK if it is fixed in the recent versions of nightly. Please let me know if you are using a more recent nightly, so I can update rust compiler on docs.rs.

**Comment by onur** [comment]
Ahh sorry ignore my first message please @ljedrz.

Looks like your link is wrong. The space between `Reduction strategies` is causing this problem:

```
/// The [evaluation order](https://en.wikipedia.org/wiki/Lambda_calculus#Reduction strategies)
```

Try to replace space with a `%20` and it will work on next release.

**Comment by ljedrz** [comment]
I'll try that, thanks. I often do releases, so I'll be able to provide feedback soon.

**Comment by ljedrz** [comment]
I'm pretty sure your suggested fix would work, but in my case I actually had to use an underscore instead of a space and it worked nicely.
