### ISSUE TITLE
Is it possible to have a "feeling lucky" search that lands on the main documentation page?

### ISSUE THREAD

**Issue by bluss** [onur/docs.rs#163]
Example use case:

- Firefox keyword search with name `docs` and pattern `https://docs.rs/releases/search?query=%s&i-am-feeling-lucky=1`
- Example use:
  1. Enter `docs serde` in the location bar
  2. Land on serde's doc front page ([here](https://docs.rs/serde/))

The benefit of going through i am feeling lucky is

1. Applying any fuzzing and parsing that the searching might do or does in the future
2. Land on search results if the thing is not found -- so the keyword can do both "summon" and search.

**Comment by bluss** [comment]
Current behaviour is that it lands [here](https://docs.rs/crate/serde/1.0.16) instead.

**Comment by onur** [comment]
Hi @bluss. Thanks for suggestion. That is exactly what I was planning for the "feeling lucky" button but due to some stupid design in [`match_version`](https://github.com/onur/docs.rs/blob/13da7b2cd11fd6ea954c1d0145490586411700a4/src/web/mod.rs#L224) it didn't work. I am planning to add some dirty fix to make it land to main documentation page but applying a fuzzy string search is not possible right now.

**Comment by bluss** [comment]
Hey that's awesome!
