### ISSUE TITLE
Add a `/:crate/newest/:...path` to `/:crate/{newest}/:...path` redirect handler

### ISSUE THREAD

**Issue by nagisa** [onur/docs.rs#26]
It would be nice to have a way to refer to some module in version-agnostic manner (in, say, README), so it gets redirected to the newest version available.

My use-case is always linking to the most recent changelog which I maintain as a [module in rustdoc](https://docs.rs/libloading/0.3.0/libloading/changelog/index.html).

**Comment by nagisa** [comment]
Also for the common version redirects like `^1` and `^1.0` which are already supported.

**Comment by onur** [comment]
I added semver support to rustdoc handler and "newest" alias to "*".

But instead of redirecting, it is serving the content. Some examples:

* <https://docs.rs/cargo/0.12.0/cargo/fn.call_main.html>
* <https://docs.rs/cargo/^0.12/cargo/fn.call_main.html>
* <https://docs.rs/cargo/^0/cargo/fn.call_main.html>
* <https://docs.rs/cargo/*/cargo/fn.call_main.html>
* <https://docs.rs/cargo/newest/cargo/fn.call_main.html>

@nagias is this good enough?

**Comment by nagisa** [comment]
That’s perfect, thank you!
