### ISSUE TITLE
docs.rs skips building some crates

### ISSUE THREAD

**Issue by carllerche** [onur/docs.rs#60]
It looks like the latest version of the futures crate (0.1.1) is not showing up: https://docs.rs/futures

**Comment by onur** [comment]
Thanks for reporting. It is fixed now.

I think this issue is related to [this human error](https://github.com/onur/docs.rs/issues/23#issuecomment-246398596). Build queue kinda messed up for crates uploaded on 10-11 September.

I am leaving this issue open to investigate crates that uploaded on 10-11 September.

**Comment by onur** [comment]
Well looks like docs.rs skipped one more crate: [winrt-0.1.0](https://github.com/onur/docs.rs/issues/23#issuecomment-250600219).

I believe docs.rs is failing to populate build queue correctly. It is working fine for the most of the time (we detected only one crate have been skipped), but it should never skip any crate.

**Comment by onur** [comment]
With #77 docs.rs should not skip anything anymore. Closing this for now.
